<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BiswaranjanD-PC" name="Command line test 2432a390-0350-408a-96f0-67ccb9f7819d" tests="3" failures="3" timestamp="27 Feb 2018 11:23:16 GMT" time="0.602" errors="0">
  <testcase name="method1" time="0.007" classname="com.selenium.demo.Demo1">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.selenium.demo.Demo1.method1(Demo1.java:16)
	at com.loylty.automationframework.TestRunner.main(TestRunner.java:123)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
	at java.lang.Thread.run(Thread.java:745)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
  <testcase name="method2" time="0.001" classname="com.selenium.demo.Demo1">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.selenium.demo.Demo1.method2(Demo1.java:26)
	at com.loylty.automationframework.TestRunner.main(TestRunner.java:123)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
	at java.lang.Thread.run(Thread.java:745)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- method2 -->
  <testcase name="method3" time="0.001" classname="com.selenium.demo.Demo1">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.selenium.demo.Demo1.method3(Demo1.java:35)
	at com.loylty.automationframework.TestRunner.main(TestRunner.java:123)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
	at java.lang.Thread.run(Thread.java:745)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- method3 -->
</testsuite> <!-- Command line test 2432a390-0350-408a-96f0-67ccb9f7819d -->
