<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BiswaranjanD-PC" name="Command line test 1b540178-4161-48a6-95fc-e76fa96cf855" tests="3" failures="1" timestamp="24 Jul 2017 05:29:19 GMT" time="180.793" errors="0">
  <testcase name="@AfterMethod getResult" time="0.0" classname="com.loylty.mobileautomation.testcases.Bom_Test">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.loylty.automationframework.common.TestClassUtil.getResult(TestClassUtil.java:117)
	at com.loylty.automationframework.TestRunner.main(TestRunner.java:121)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
	at java.lang.Thread.run(Thread.java:745)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod getResult -->
  <testcase name="@BeforeMethod setup" time="0.0" classname="com.loylty.mobileautomation.testcases.Bom_Test">
    <skipped/>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase name="@AfterMethod teardown" time="0.0" classname="com.loylty.mobileautomation.testcases.Bom_Test">
    <skipped/>
  </testcase> <!-- @AfterMethod teardown -->
  <testcase name="@AfterMethod getResult" time="0.0" classname="com.loylty.mobileautomation.testcases.Bom_Test">
    <skipped/>
  </testcase> <!-- @AfterMethod getResult -->
  <testcase name="@BeforeMethod setup" time="0.0" classname="com.loylty.mobileautomation.testcases.Tmb_Test">
    <skipped/>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase name="@AfterMethod teaardown" time="0.0" classname="com.loylty.mobileautomation.testcases.Tmb_Test">
    <skipped/>
  </testcase> <!-- @AfterMethod teaardown -->
  <testcase name="@AfterMethod getResult" time="0.0" classname="com.loylty.mobileautomation.testcases.Tmb_Test">
    <skipped/>
  </testcase> <!-- @AfterMethod getResult -->
  <testcase name="recharge" time="149.879" classname="com.loylty.mobileautomation.testcases.Bom_Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.loylty.mobileautomation.testcases.Bom_Test.recharge(Bom_Test.java:101)
	at com.loylty.automationframework.TestRunner.main(TestRunner.java:121)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
	at java.lang.Thread.run(Thread.java:745)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- recharge -->
  <testcase name="verify_humberger" time="0.0" classname="com.loylty.mobileautomation.testcases.Bom_Test">
    <skipped/>
  </testcase> <!-- verify_humberger -->
  <testcase name="verify_humberger" time="0.0" classname="com.loylty.mobileautomation.testcases.Tmb_Test">
    <skipped/>
  </testcase> <!-- verify_humberger -->
</testsuite> <!-- Command line test 1b540178-4161-48a6-95fc-e76fa96cf855 -->
