<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BiswaranjanD-PC" name="Command line test 567675ed-7e02-45ff-bac7-a92b68408518" tests="2" failures="1" timestamp="8 Dec 2017 07:22:46 GMT" time="297.956" errors="0">
  <testcase name="userMangement_MPOINT_B" time="159.626" classname="com.loylty.mobileautomation.testcases.Mpoint_B_Test">
    <failure type="java.lang.AssertionError" message="User management unsucessful expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: User management unsucessful expected [true] but found [false]
	at com.loylty.mobileautomation.testcases.Mpoint_B_Test.userMangement_MPOINT_B(Mpoint_B_Test.java:82)
	at com.loylty.automationframework.TestRunner.main(TestRunner.java:116)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
	at java.lang.Thread.run(Thread.java:745)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- userMangement_MPOINT_B -->
  <testcase name="forgotpassword_KVB" time="125.856" classname="com.loylty.mobileautomation.testcases.Kvb_Test"/>
</testsuite> <!-- Command line test 567675ed-7e02-45ff-bac7-a92b68408518 -->
