<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BiswaranjanD-PC" name="Command line test 36950f38-acca-4814-8523-abd5a802c279" tests="2" failures="1" timestamp="21 Jul 2017 10:26:50 GMT" time="111.773" errors="0">
  <testcase name="@AfterMethod getResult" time="0.0" classname="com.loylty.mobileautomation.testcases.Bom_Test">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.loylty.automationframework.common.TestClassUtil.getResult(TestClassUtil.java:114)
	at com.loylty.automationframework.TestRunner.main(TestRunner.java:121)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod getResult -->
  <testcase name="@AfterMethod getResult" time="0.0" classname="com.loylty.mobileautomation.testcases.Bom_Test">
    <skipped/>
  </testcase> <!-- @AfterMethod getResult -->
  <testcase name="@AfterTest teardown" time="0.0" classname="com.loylty.mobileautomation.testcases.Bom_Test">
    <skipped/>
  </testcase> <!-- @AfterTest teardown -->
  <testcase name="recharge" time="98.436" classname="com.loylty.mobileautomation.testcases.Bom_Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.loylty.mobileautomation.testcases.Bom_Test.recharge(Bom_Test.java:98)
	at com.loylty.automationframework.TestRunner.main(TestRunner.java:121)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- recharge -->
  <testcase name="verify_humberger" time="0.0" classname="com.loylty.mobileautomation.testcases.Bom_Test">
    <skipped/>
  </testcase> <!-- verify_humberger -->
</testsuite> <!-- Command line test 36950f38-acca-4814-8523-abd5a802c279 -->
